# -*- coding: utf-8 -*-
"""Practical No 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nd9vL63cO5hWpT1NyfIN9jn-BcZsP3sI

1. Extract Sample document and apply following document preprocessing methods:
Tokenization, POS Tagging, stop words removal, Stemming and Lemmatization.
2.  Create representation of document by calculating Term Frequency and Inverse Document Frequency.
"""

pip install nltk scikit-learn

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag

from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

document = """
Natural Language Processing is a field of Artificial Intelligence that focuses on
the interaction between computers and humans using natural language.
"""

print("Original Document:\n", document)

tokens = word_tokenize(document)
print("\nTokens:\n", tokens)

pos_tags = pos_tag(tokens)
print("\nPOS Tags:\n", pos_tags)

stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

print("\nAfter Stopword Removal:\n", filtered_tokens)

stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_tokens]
print("\nStemmed Words:\n", stemmed_words)

lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_tokens]
print("\nLemmatized Words:\n", lemmatized_words)

documents = [
    document,
    "Artificial Intelligence and Machine Learning are closely related fields.",
    "Natural Language Processing enables computers to understand human language."
]

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)
print("\nFeature Names:\n", vectorizer.get_feature_names_out())
print("\nTF-IDF Matrix:\n", tfidf_matrix.toarray())