# -*- coding: utf-8 -*-
"""Practical No 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WyOeTGdu_G6yABHIFBHQc_Rob58SniK9

# **DATA WRANGLING 2**
Create an “Academic performance” dataset of students and perform the following operations using Python.
1. Scan all variables for missing values and inconsistencies. If there are missing values and/or
inconsistencies, use any of the suitable techniques to deal with them.
2. Scan all numeric variables for outliers. If there are outliers, use any of the suitable techniques to deal
with them.
3. Apply data transformations on at least one of the variables. The purpose of this transformation should be
one of the following reasons: to change the scale for better understanding of the variable, to convert a
non-linear relation into a linear one, or to decrease the skewness and convert the distribution into a normal
distribution.
4. Reason and document your approach properly.
"""

import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    "Student_ID":[1,2,3,4,5,6,7,8,9,10],
    "Study_Hours":[2,4,6,8,np.nan,5,7,20,3,4],
    "Attendance":[85,90,88,95,80,78,92,110,75,np.nan],
    "Assignment_Score":[70,75,80,85,90,65,72,95,68,74],
    "Exam_Score":[65,70,78,88,92,60,75,98,66,72],
    "Gender":["M","F","M","F","F","M","M","F","F","M"]
}

df = pd.DataFrame(data)
print(df)

print(df.isnull().sum())

df["Study_Hours"].fillna(df["Study_Hours"].mean(), inplace=True)
df["Attendance"].fillna(df["Attendance"].mean(), inplace=True)

print(df.isnull().sum())

print(df[df["Attendance"] > 100])

df.loc[df["Attendance"] > 100, "Attendance"] = 100

plt.figure(figsize=(8,5))
sns.boxplot(data=df[["Study_Hours","Attendance","Assignment_Score","Exam_Score"]])
plt.title("Boxplot for Outlier Detection")
plt.show()

Q1 = df["Study_Hours"].quantile(0.25)
Q3 = df["Study_Hours"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df["Study_Hours"] = np.where(df["Study_Hours"] > upper, upper, df["Study_Hours"])

df["Exam_Percentage"] = (df["Exam_Score"] / 100) * 100

df["Log_Study_Hours"] = np.log(df["Study_Hours"])

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
sns.histplot(df["Study_Hours"], kde=True)
plt.title("Before Transformation")

plt.subplot(1,2,2)
sns.histplot(df["Log_Study_Hours"], kde=True)
plt.title("After Log Transformation")

plt.show()

print(df)

