# -*- coding: utf-8 -*-
"""Practical No 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gKMCvA-JzATXgbWiaRjHnB0Yaw4EaKj

1. Implement logistic regression using Python/R to perform classification on
Social_Network_Ads.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on the given dataset.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

df = pd.read_csv("Social_Network_Ads.csv")

df.head()

df.columns
df.shape

df = df[['Age', 'EstimatedSalary', 'Purchased']]

X = df[['Age', 'EstimatedSalary']].values
y = df['Purchased'].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0
)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\nPredicted values:\n", y_pred[:10])

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:\n", cm)

TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

accuracy = (TP + TN) / (TP + TN + FP + FN)
error_rate = (FP + FN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)

print("\nPerformance Metrics:")
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

# Assuming you already have y_test and y_pred
cm = confusion_matrix(y_test, y_pred)

# Plot
plt.figure()
plt.imshow(cm)

# Labels
plt.title("Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")

# Tick marks
classes = ['No Purchase', 'Purchase']
plt.xticks(np.arange(len(classes)), classes)
plt.yticks(np.arange(len(classes)), classes)

# Add numbers inside boxes
for i in range(len(cm)):
  for j in range(len(cm)):
    plt.text(j, i, cm[i][j], ha="center", va="center")

plt.colorbar()
plt.show()

