# -*- coding: utf-8 -*-
"""Practical No 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1XgFSO9fsOZgpCjtvE8HU7eaatcciZk

# **Data Visualization 1**

1. Use the inbuilt dataset 'titanic'. The dataset contains 891 rows and contains information about the
passengers who boarded the unfortunate Titanic ship. Use the Seaborn library to see if we can find any patterns in the data.
2. Write a code to check how the price of the ticket (column name: 'fare') for each passenger is distributed by plotting a histogram.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('titanic')

print(df.head())
print(df.info())

sns.countplot(x = 'survived', data = df)
plt.title("Survival Count")
plt.show()

sns.countplot(x = 'survived', hue = 'sex', data = df)
plt.title("Survival by Gender")
plt.show()

sns.countplot(x = 'survived', hue = 'pclass', data = df)
plt.title("Survival by Passenger Class")
plt.show()

sns.histplot(df['age'].dropna(), bins = 30, kde = True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.show()

sns.histplot(df['fare'].dropna(), bins = 30, kde = True)
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Count")
plt.show()

sns.boxplot(x = 'pclass', y = 'fare', data = df)
plt.title("Fare by Passenger Class")
plt.xlabel("Passenger Class")
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot = True, cmap = 'coolwarm')
plt.title("Correlation Heatmap")
plt.show()