# -*- coding: utf-8 -*-
"""Practical No 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bDRFogY9Sv2JZ4WHZzMlhTvHXWBJLdtK

# **DATA WRANGLING 1**
Perform the following operations using Python on any open-source dataset (e.g., data.csv)
Import all the required Python Libraries.
1. Locate open-source data from the web (e.g. https://www.kaggle.com).
2. Provide a clear description of the data and its source (i.e., URL of the web site).
3. Load the Dataset into the pandas data frame.
4. Data Preprocessing: check for missing values in the data using pandas insult(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the
data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set.
If variables are not in the correct data type, apply proper type conversions.
6. Turn categorical variables into quantitative variables in Python.
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv("Iris.csv", header=0)
print(df.head(n=5))

df.isnull()

df.shape

df.size

df.columns

df.head()

df.tail()

df.dtypes

df.isnull().sum()

df.isna()

df.sample()

df.info()

df['Id']

df[['Id','SepalLengthCm']]

df.iloc[0]

df.iloc[3:4]

from sklearn import preprocessing

x = df['SepalLengthCm'].values.astype(float)

min_max_scaler = preprocessing.MinMaxScaler()

x = x.reshape(-1, 1)
x_scaled = min_max_scaler.fit_transform(x)

df_normalized = pd.DataFrame(x_scaled)

df_normalized

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.scatterplot(x='SepalLengthCm', y='SepalWidthCm', hue='Species', data=df)
plt.show()

sns.boxplot(data=df.drop('Id',axis=1))
plt.show()

