# -*- coding: utf-8 -*-
"""Practical No 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyuhIant2ezWAWYc1XfUEAEx5nCakueK

# **DATA VISUALIZATION 2**
Data Visualization III Download the Iris flower dataset or any other dataset
into a DataFrame. (e.g., https://archive.ics.uci.edu/ml/datasets/Iris ). Scan
the dataset and give the inference as:
1. List down the features and their types (e.g., numeric, nominal) available
in the dataset.
2. Create a histogram for each feature in the dataset to illustrate the feature
distributions.
3. Create a boxplot for each feature in the dataset. 4. Compare distributions
and identify outliers
4. Compare distributions and identify outliers
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('iris')
print(df.head())

print(df.info())

df.hist(figsize=(10, 8))
plt.suptitle("Histograms of Iris Features")
plt.show()

plt.figure(figsize=(10, 6))

for i, column in enumerate(df.columns[:-1], 1):
  plt.subplot(2, 2, i)
  sns.boxplot(y=df[column])
  plt.title(column)

plt.tight_layout()
plt.show()

# Copy dataset (safe practice)
df_clean = df.copy()

# Select only numeric columns
numeric_cols = df_clean.select_dtypes(include=['float64', 'int64']).columns

# Remove outliers using IQR
for col in numeric_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

# Check result
print("Original Shape:", df.shape)
print("After Removing Outliers:", df_clean.shape)

import matplotlib.pyplot as plt

df.boxplot(figsize=(8,5))
plt.title("Before Removing Outliers")
plt.show()

df_clean.boxplot(figsize=(8,5))
plt.title("After Removing Outliers")
plt.show()