# -*- coding: utf-8 -*-
"""Practical No 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnS8vkz0TX0nqncVJuAUUTNqAJAex1_q

**Create a Linear Regression Model using Python/R to predict
home prices using Boston Housing Dataset** (https://www.kaggle.com/c/boston-housing). The
Boston Housing dataset contains information about various houses in Boston through different
parameters. There are 506 samples and 14 feature variables in this dataset.
The objective is to predict the value of prices of the house using the given features.
"""

import pandas as pd

url = " https://raw.githubusercontent.com/selva86/datasets%20/master/BostonHousing.csv"
df = pd.read_csv(url)

df.head()

print(df.shape)
print(df.columns)
df.describe()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

print(df.isnull().sum())

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

X=df.drop("medv",axis=1)
y=df["medv"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)

print("Mean Squared Error:",mse)
print("Root Mean Squared Error:",rmse)
print("R2 Score:",r2)

plt.scatter(y_test,y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()

coefficients = pd.DataFrame(model.coef_, X.columns, columns=["Coefficient"])
print(coefficients)

