# -*- coding: utf-8 -*-
"""Practical No 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dcv_MfuL-P14Zu24Z0GmJtG6EXxN9evp

1. Implement Simple Naïve Bayes classification algorithm using Python/R on  iris.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

df = pd.read_csv('Iris.csv')
df.head()

# Features (X) and Target (y)
X = df.iloc[:, :-1]   # first 4 columns
y = df.iloc[:, -1]    # last column (species)
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

classes = np.unique(y)

for i, cls in enumerate(classes):
  TP = cm[i, i]
  FN = sum(cm[i, :]) - TP
  FP = sum(cm[:, i]) - TP
  TN = np.sum(cm) - (TP + FP + FN)

  accuracy = (TP + TN) / np.sum(cm)
  error_rate = 1 - accuracy
  precision = TP / (TP + FP) if (TP + FP) != 0 else 0
  recall = TP / (TP + FN) if (TP + FN) != 0 else 0

  print(f"\nClass: {cls}")
  print(f"TP={TP}, FP={FP}, TN={TN}, FN={FN}")
  print(f"Accuracy={accuracy:.3f}")
  print(f"Error Rate={error_rate:.3f}")
  print(f"Precision={precision:.3f}")
  print(f"Recall={recall:.3f}")

overall_accuracy = np.trace(cm) / np.sum(cm)
print("\nOverall Accuracy:", overall_accuracy)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=classes,
            yticklabels=classes)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()