# -*- coding: utf-8 -*-
"""Practical No 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mn-bA2Yj8dBGWVmx4R80PYdHezoy0qDz

# **DESCRIPTIVE STATISTICS- MEASURES OF CENTRAL TENDENCY AND VARIABILITY**
Perform the following operations on any open-source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset
(age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable.
For example, if your categorical variable is age groups and quantitative variable is income, then
provide summary statistics of income grouped bythe age groups. Create a list that contains a
numeric value for each response to the categorical variable.
2. Write a Python program to display some basic statistical details like percentile, mean, standard
deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris- versicolor’ of iris.csv dataset.
"""

import pandas as pd
import numpy as np

url = " https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"
df = pd.read_csv(url)

df.head()

print(df.info())
print(df.describe())

grouped = df.groupby("species")

summary_stats = grouped.agg(['mean','median','min','max','std'])
print(summary_stats)

setosa_list = df[df['species']=='setosa']['sepal_length'].tolist()
versicolor_list = df[df['species']=='versicolor']['sepal_length'].tolist()
virginica_list = df[df['species']=='virginica']['sepal_length'].tolist()

print("Setosa:", setosa_list[:5])
print("Versicolor:", versicolor_list[:5])
print("Virginica:", virginica_list[:5])

setosa = df[df['species'] == 'setosa']
versicolor = df[df['species'] == 'versicolor']
virginica = df[df['species'] == 'virginica']

print("Statistics for Iris Setosa")
print(setosa.describe())

print("\nStatistics for Iris Versicolor")
print(versicolor.describe())

print("\nStatistics for Iris Virginica")
print(virginica.describe())

print("Percentiles for Sepal Length")

print("25th percentile:", np.percentile(df['sepal_length'],25))
print("50th percentile:", np.percentile(df['sepal_length'],50))
print("75th percentile:", np.percentile(df['sepal_length'],75))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.boxplot(x="species", y="sepal_length", data=df)

plt.title("Sepal Length Distribution by Species")
plt.xlabel("Species")
plt.ylabel("Sepal Length")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["sepal_length"], bins=20, kde=True)

plt.title("Distribution of Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x="sepal_length", y="petal_length", hue="species", data=df)

plt.title("Sepal Length vs Petal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Petal Length")
plt.show()

sns.pairplot(df, hue="species")
plt.show()

species_mean = df.groupby("species").mean()
species_mean.plot(kind="bar", figsize=(8,5))

plt.title("Mean Measurements by Species")
plt.ylabel("Mean Value")
plt.show()

