# -*- coding: utf-8 -*-
"""Practical No 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfTMWdbA7lL7y_XKVHpPpFDbk7YQJz85

# **DATA VISUALIZATION 2**


1.  Use the inbuilt dataset 'titanic' as used in the above problem. Plot a box plot for distribution of age with respect to each gender along with the information about whether they survived or not. (Column names : 'sex' and 'age')
2.  Write observations on the inference from the above statistics.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('titanic')

print(df.head())
print(df.info())

print("First 5 rows:\n", df.head())
print("\nDataset Info:\n")
print(df.info())
print("\nStatistical Summary:\n", df.describe())

df = df.dropna(subset=['age'])

sns.boxplot(x='sex', y='age', hue='survived', data=df)
plt.title("Age Distribution by Gender and Survival")
plt.xlabel("Gender")
plt.ylabel("Age")
plt.legend(title="Survived (0 = No, 1 = Yes)")
plt.show()

sns.violinplot(x='sex', y='age', hue='survived', data=df, split=True)
plt.title("Detailed Age Distribution (Violin Plot)")
plt.show()

